=== ShylkoVad/TMS/src/by/teachmeskils/homeworks/hw_28042023/folderXSD3/schemaXSD3.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--Простые элементы-->
    <xs:simpleType name="stringtype">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <!--Сложные элементы-->
    <xs:complexType name="doctortype">
        <xs:sequence>
            <xs:element name="fullName" type="stringtype"/>
            <xs:element name="jobTitle" type="stringtype"/>
            <xs:element name="department" type="stringtype"/>
            <xs:element name="workExperience" type="stringtype"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="nursetype">
        <xs:sequence>
            <xs:element name="fullName" type="stringtype"/>
            <xs:element name="jobTitle" type="stringtype"/>
            <xs:element name="department" type="stringtype"/>
            <xs:element name="workExperience" type="stringtype"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="hospitaltype">
        <xs:sequence>
            <xs:element name="doctor" type="doctortype" maxOccurs="unbounded"/>
            <xs:element name="nurse" type="nursetype" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="hospital" type="hospitaltype"/>

</xs:schema>

=== ShylkoVad/TMS/src/by/teachmeskils/homeworks/hw_28042023/folderXSD3/hospitalXSD3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemaXSD3.xsd">
    <doctor>
        <fullName>Чумик Сергей Иванович</fullName>
        <jobTitle>Заведующий отделением</jobTitle>
        <department>Хирургическое отделений</department>
        <workExperience>25 лет</workExperience>
    </doctor>
    <doctor>
        <fullName>Садовская Елена Петровна</fullName>
        <jobTitle>Офтальмолог</jobTitle>
        <department>Глазное отделение</department>
        <workExperience>5 лет</workExperience>
    </doctor>
    <doctor>
        <fullName>Иванов Петр Сергеевич</fullName>
        <jobTitle>Хирург</jobTitle>
        <department>1-ое хирургическое отделение</department>
        <workExperience>11 лет</workExperience>
    </doctor>
    <doctor>
        <fullName>Климова Анастасия Александровна</fullName>
        <jobTitle>Стоматолог-ортопед</jobTitle>
        <department>Ортопедическое отделение</department>
        <workExperience>15 лет</workExperience>
    </doctor>
    <nurse>
        <fullName>Кирсанова Светлана Валерьевна</fullName>
        <jobTitle>Старшая медсестра</jobTitle>
        <department>1-ое хирургическое отделение</department>
        <workExperience>14 лет</workExperience>
    </nurse>
    <nurse>
        <fullName>Герасимчук Татьяна Валентиновна</fullName>
        <jobTitle>Участковая медсестра</jobTitle>
        <department>Детское отделение</department>
        <workExperience>2 года</workExperience>
    </nurse>
    <nurse>
        <fullName>Куликова Диана Аркадьевна</fullName>
        <jobTitle>Операционная медсестра</jobTitle>
        <department>2-ое педиатрическое отделение</department>
        <workExperience>8 лет</workExperience>
    </nurse>
    <nurse>
        <fullName>Литвинова Светлана Ивановна</fullName>
        <jobTitle>Процедурная медсестра</jobTitle>
        <department>Кардиологическое отделение</department>
        <workExperience>1 год</workExperience>
    </nurse>
</hospital>
